#  动态压力传感器
PressureSensor:
  -
    id: 1
    describer: "1-1"
  -
    id: 2
    describer: "1-2"

# 温度传感器
TemperatureSensor:
  -
    id: 1
    describer: "2-1"
  -
    id: 2
    describer: "2-2"

#  振动速度传感器
VibrationVelocitySensor:
  -
    id: 1
    describer: "3-1"
  -
    id: 2
    describer: "4-1"

#  震动加速度传感器
VibrationAccelerationSensor:
  -
    id: 2
    describer: "4-1"
  -
    id: 3
    describer: "4-2"

#  位移传感器
DisplacementSensor:
  -
    id: 1
    describer: "5-1"
  -
    id: 2
    describer: "5-2"

#   TDC相位传感器
TDCPhaseSensor:
  -
    id: 1
    describer: "6-1"
  -
    id: 2
    describer: "6-2"